# fly.toml app configuration file generated for chandoanviemphoi-kitl4a-lively-glade-3725 on 2026-03-16T11:30:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chandoanviemphoi-kitl4a-lively-glade-3725'
primary_region = 'sin'

[build]

[processes]
  app = 'python backend/app/main.py'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpus = 4
  memory_mb = 8192
